### PR TITLE
CRDGEN-272

### PR DESCRIPTION
**Pull request by ZontaNicola**
Changed the weights a bit so that when picking the "central" ring of a system we tend to pick rings that share more atoms with other rings
also now when adding a side ring we try to align it with the already drawn ring that shares the most atoms with it

added a test

### CODE REVIEW

**Comment by d-b-w** [comment]
@ZontaNicola -
Could you add an image to this PR that demonstrates what this accomplishes?

**Comment by d-b-w** [comment]
@ZontaNicola -
Please add a test function that checks to see if there are any crossed bonds.

**Comment by ZontaNicola** [comment]
> @ZontaNicola -
> Could you add an image to this PR that demonstrates what this accomplishes?

perfection itself ;)
Screenshot 2021-04-27 at 11 23 16

**Review by rachelnwalker — APPROVED** [review]
looks good to me! :)

**Pull request merged**
