### PR TITLE
better shape of rings after minimization - CRDGEN-260

### PR DESCRIPTION
**Pull request by ZontaNicola**
this increases strength of constraints for non-macrocycle rings and make minimization more efficient. (we used to run it twice).
added automated test on one of the structures linked to the case (CRDGEN-260)
manual checked the others

minimization still doesn't seem to converge on these structures (we're probably wasting computation time there) but the resut looks good

### CODE REVIEW

**Comment by d-b-w** [comment]
Looks like the build error is real:

    D:\a\1\s\CoordgenMinimizer.cpp(76): warning C4305: 'argument': truncation from 'double' to 'float'

**Comment by d-b-w** [comment]
Hey @ZontaNicola  - I'm good with this, but it currently has merge conflicts. Would you address those so I can merge this?

By the way - if you do your development in a branch (rather than on master), I can fix merge failures myself.

**Comment by d-b-w** [comment]
Thanks, @ZontaNicola

**Comment by ZontaNicola** [comment]
@d-b-w I didn't get any conflicts merging this, just wanted to double check

**Comment by d-b-w** [comment]
Looks good

**Pull request merged**
